version: '2.3'

services:
  dev:
    container_name: dev
    runtime: nvidia
    restart: always
    build:
      context: ./
      dockerfile: docker/dev/dockerfile
    env_file:
      - "docker/env.env"
    volumes:
      - ${PWD}:/workspace
    ports:
      - "10000:8000"
      - "10022:22"
    stdin_open: true
    tty: true

volumes:
  dataset:
    driver: local
    driver_opts:
      type: none
      device: /media/hdd/dataset
      o: bind
